app/models.py
from flask_login import UserMixin
from .firebase_service import get_user_by_key_and_password

class UserData:
    def __init__(self, username, password, email, role):
        self.username = username
        self.password = password
        self.email = email
        self.role = role

class UserModel(UserMixin):
    def __init__(self, user_data):
        """
        :param user_data: UserData
        """
        self.id = user_data.username
        self.password = user_data.password
        self.email = user_data.email
        self.role = user_data.role

    @staticmethod
    def query(username, password):
        # Utiliza el método para obtener el usuario desde Firestore
        user_data = get_user_by_key_and_password(username, password)
        if user_data:
            return UserModel(UserData(
                username=user_data['nombre_usuario'],
                password=user_data['clave_usario'],
                email=user_data['correo_usuario'],
                role=user_data['rol_usario']
            ))
        return None  # Si no se encuentra el usuario
  

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField,PasswordField
from wtforms.validators import DataRequired, Email

class ContactForm(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired()])
    email = StringField('Correo Electrónico', validators=[DataRequired(), Email()])
    subject = StringField('Tema', validators=[DataRequired()])
    comments = TextAreaField('Comentario', validators=[DataRequired()])
    enviar = SubmitField('Enviar')

class LoginForm(FlaskForm):
    username = StringField('Nombre de usuario', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Enviar')
class Signup(FlaskForm):
    username = StringField('Nombre de usuario', validators=[DataRequired()])
    password = StringField('Password', validators=[DataRequired()])
    email=StringField('Correo del usuario', validators=[DataRequired(),Email()])
    submit = SubmitField('Crear Usuario')
class Publicacion(FlaskForm):
    title= StringField('Titulo de la publicacion', validators=[DataRequired()])
    historia=TextAreaField('Historia', validators=[DataRequired()])
    observacion=TextAreaField('Observacion', validators=[DataRequired()])
    submit = SubmitField('Crear Publicacion')
class Delete(FlaskForm):
    submit=SubmitField('Eliminar')
class Update(FlaskForm):
    submit=SubmitField('Actualizar')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import Config
from app.auth import auth
from .routes import main

def create_app():
    app = Flask(__name__)
    bootstrap = Bootstrap(app)
    app.config.from_object(Config)
    
    app.register_blueprint(main)  # Registro del blueprint 'main'
    app.register_blueprint(auth)  # Registro del blueprint 'auth'
    
    return app

app/main/routes.py
# app/routes.py
from . import main
from flask import render_template, redirect, url_for, session, flash
from app.forms import ContactForm


@main.route('/')
def index():
    
    return render_template('inicio.html')

@main.route('/nosotros')
def nosotros():
    return render_template('nosotros.html')

@main.route('/anuncios')
def anuncios():
    return render_template('anuncios.html')

@main.route('/blog')
def blog():
    return render_template('blog.html')



@main.route("/contactanos", methods=['GET', 'POST'])
def contactanos_view():
    form = ContactForm()
    if form.validate_on_submit():
        name = form.name.data
        session['name'] = name
        flash('Muchas gracias por la sugerencia!')
        return redirect(url_for('main.contactanos_view'))
    return render_template('comentario.html', form=form)
@main.route('/go-to-login')
def go_to_login():
    # Aquí rediriges al blueprint `auth`, a la ruta `login`
    return redirect(url_for('auth.login'))

app/routes.py
# app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, make_response
from .forms import ContactForm
from app.firebase_service import put_commit,get_comment,get_all_blogs
from datetime import date,datetime
main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('inicio.html')

@main.route('/nosotros')
def nosotros():
    return render_template('nosotros.html')

@main.route('/anuncios')
def anuncios():
    return render_template('anuncios.html')

@main.route('/blog')
def blog():
    blogs = get_all_blogs()
    # Formatear fecha si es necesario
    for blog in blogs:
        if 'fecha_publicacion' in blog:
            # Verificar si 'fecha_publicacion' es del tipo DatetimeWithNanoseconds o similar
            if isinstance(blog['fecha_publicacion'], datetime):
                blog['fecha_publicacion'] = blog['fecha_publicacion'].strftime('%d/%m/%Y')
    context = {
        'blogs': blogs,
    }
    return render_template('blog.html', **context)

@main.route("/verficarComentPost")
def post_aprob_coment():
    response = make_response(redirect('/contactanos'))
    return response

@main.route("/contactanos", methods=['GET', 'POST'])
def contactanos_view():
    form = ContactForm()
    if form.validate_on_submit():
        name = form.name.data
        email= form.email.data
        subject=form.subject.data
        comments=form.comments.data
        id=email+subject
        contacto=get_comment(id)
        if not contacto:
            put_commit(id,comments,subject,email,name)
            flash('Muchas gracias por la sugerencia!')
            return redirect(url_for('main.contactanos_view'))
        else:
            flash('Ya nos registraste este comentario, espera a que lo resolvamos')
            return redirect(url_for('main.contactanos_view'))

    return render_template('comentario.html', form=form)

@main.route('/go-to-login')
def go_to_login():
    return redirect(url_for('auth.login'))

app/templates/Inicio.html
{% extends 'index.html' %}
<title>{% block title %}
    Pagina inicial
  {% endblock title %}</title>
  {% block content %}
  <div class="recuadro">
    <section class="content seccion">
        <h2 class="fw-300 center-text recuadro-titulo "> Mas sobre Nosotros</h2>
        <div class="posd">
          <div class="iconos">
            <img src="{{ url_for('static', filename='imagenes/descripcion.png') }}" alt="descripcion">
              <h3 class="encabezado ">Breve descripcion del Blog</h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis iste fugit, mollitia est maxime nobis, incidunt explicabo eos dolor in repudiandae praesentium soluta quae dicta et ea ratione odio. Mollitia!</p>
            </div>
          <div class="iconos">
            <img src="{{ url_for('static', filename='imagenes/equipo.png') }}" alt="equipo">
            <h3 class="encabezado ">Equipo del Blog</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse aut numquam labore aperiam autem ipsa laudantium vero ipsum quos ex, cum repellendus, perferendis aliquam, repellat vel animi nihil delectus perspiciatis.</p>
          </div>
          <div class="iconos">
            <img src="{{ url_for('static', filename='imagenes/proposito.png') }}" alt="proposito">
            <h3 class="encabezado ">Proposito del Blog</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse aut numquam labore aperiam autem ipsa laudantium vero ipsum quos ex, cum repellendus, perferendis aliquam, repellat vel animi nihil delectus perspiciatis.</p>
          </div>
          <div class="iconos">
            <img src="{{ url_for('static', filename='imagenes/historia.png') }}" alt="origen">
            <h3 class="encabezado ">Origen del Blog</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse aut numquam labore aperiam autem ipsa laudantium vero ipsum quos ex, cum repellendus, perferendis aliquam, repellat vel animi nihil delectus perspiciatis.</p>
          </div>
        </div>
    </section>
    <main>
      <h2 class="fw-300 center-text recuadro-titulo"> Atracciones</h2>
      <div class="content-Anunc">
        <div class="anun">
          <img src="{{ url_for('static', filename='imagenes/piedras del tunjo.jpg') }}" alt="imagen atraccion">
            <div class="contenido_anun">
              <h3>Piedras del Tunjo</h3>
                <p>El Parque Arqueológico de Facatativá, también conocido como Piedras del Tunjo, es un conjunto de pictogramas cuyo origen exacto aún se desconoce</p>
                <div class="icono-info" >
                  <ul>
                    <li>
                      <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio" >
                      <p>$10.000</p>
                    </li>
                    <li>
                      <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                      <p>Calle 5# 12A-10</p>
                    </li>
                    <li>
                      <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                      <p>8:00am - 4:00pm</p>
                    </li>
                  </ul>
                </div>
              <a href="http://www.colparques.net/FACA" class="boton boton-ver d_display" target="_blank"> ver atraccion</a>
            </div>
        </div>
        <div class="anun">
          <img src="{{ url_for('static', filename='imagenes/KYSQA.jpg') }}" alt="imagen atraccion">
            <div class="contenido_anun">
              <h3> KYQA MHUYSQA</h3>
              <p>El Parque Kyqa Mhuysqa es un espacio temático y centro de eventos inspirado en la cultura colombiana y nuestros antepasados muiscas</p>
              <div class="icono-info" >
                <ul>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio" >
                    <p>$49.000</p>
                  </li>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                    <p>Los llanitos, Zipalandia, Facatativá</p>
                  </li>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                    <p>sabados y domingo 10a.m–7p.m</p>
                  </li>
                </ul>
              </div>
              <a href="https://acolap.org.co/kyqa-mhuysqa/" class="boton boton-ver d_display" target="_blank"> ver atraccion</a>
            </div>
        </div>
        <div class="anun">
          <img src="{{ url_for('static', filename='imagenes/parque.jpeg') }}" alt="imagen atraccion">
            <div class="contenido_anun">
              <h3>Parque de los Niños</h3>
              <p> El Parque de los Niños es un escenario recreo deportivo ubicado en la ciudad de Facatativá. Ofrece actividades para toda la familia y cuenta con instalaciones para el entretenimiento y la diversión. </p>
              <div class="icono-info" >
                <ul>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio" >
                    <p>gratis</p>
                  </li>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                    <p> Carrera 2 #1-102, en Facatativá</p>
                  </li>
                  <li>
                    <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                    <p>Abierto los jueves, viernes, sábados y domingos, con horarios específicos</p>
                  </li>
                </ul>
              </div>
              <a href="https://www.facatativa-cundinamarca.gov.co/noticias/el-parque-de-los-ninos-un-lugar-para-la-diversion" class="boton boton-ver d_display" target="_blank"> ver atraccion</a>
            </div>
        </div>      
      </div>
      <div class="ver_td">
        <a href="{{ url_for('main.anuncios') }}" class="boton boton-verc">ver Todas</a>
      </div>  
      <br>
    </main>
    <section class="imagen-contacto">
      <div class="content contactos">
        <h3>Disfruta y aprende</h3>
        <p>si el sitio turistico no esta registrado
          <br>aun, contactanos</p>
          <a href="{{ url_for('main.contactanos_view') }}" class="boton boton-verc">contactanos</a>
      </div>
    </section>
    <div class="seccion-inferior content">
        <section class="seccion-blog">
          <div class="texto-entrada">
            <a href="{{ url_for('main.blog') }}">
              <h3>Nuestro Blog</h3>
            </a>
          </div>
          <article class="entrada-blog">
          <div class="imagen-blog">
            <img src="{{ url_for('static', filename='imagenes/casa de la cultura.jpeg') }}" alt="blog">
          </div>
          <div class="texto-entrada">
            <a href="{{ url_for('main.blog') }}">
              <h4> La Casa de la Cultura </h4>
            </a>
            <p> Escrito en:<span>13/06/2024</span> por:<span> admin</span></p>
            <p> Las escuelas de formación artística que funcionarán aquí 
             <br> abarcan modalidades como escultura, pintura, 
             <br> modelado en 3D, banda sinfónica y fiestera.</p>
          </div>
          </article>
          <article class="entrada-blog">
          <div class="imagen-blog">
            <img src="{{ url_for('static', filename='imagenes/clima.jpg') }}" alt="blog">
          </div>
          <div class="texto-entrada">
            <a href="{{ url_for('main.blog') }}">
              <h4> El Clima Templado </h4>
            </a>
            <p> Escrito en:<span>13/06/2024</span> por:<span> admin</span></p>
            <p>Facatativá se caracteriza por un clima templado y
              <br> bastante estable a lo largo del año. Las temperaturas 
               <br>suelen oscilar entre los 10 y 20 grados centígrados.</p>
          </div>
          </article>
          <article class="entrada-blog">
          <div class="imagen-blog">
            <img src="{{ url_for('static', filename='imagenes/arte.jpeg') }}" alt="blog">
          </div>
          <div class="texto-entrada">
            <a href="{{ url_for('main.blog') }}">
              <h4> El Arte en Facatativá </h4>
            </a>
            <p> Escrito en:<span>13/06/2024</span> por:<span> admin</span></p>
            <p> Facatativá tiene una escena artística emergente
              <br> que incluye tanto artistas locales como
              <br> visitantes.</p>
          </div>
          </article>
        </section>
        <section class="seccion-commet">
          <h3>Comentarios de nuestro servicio</h3>
            <div class="testimonio">
              <header>
                <p> Testimonio </p> 
              </header>
                <blockquote class='forma' >*este es un testimonio conmevedor* picsascasva vasmoavpas uwu puedes ser cualquier cosa que quieres; sin embargo, en tu caso deberías apuntar bajo.</blockquote>
              <p> -Elver Gudo</p>
            </div>
        </section>

    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> <!-- Funcion de las alertas-->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 
{% endblock content %}

app/templates/anuncios.html
{% extends 'index.html' %}

<title>
  {% block title %}
      Anuncios
  {% endblock title %}
</title>
{% block content %}

<div class="recuadro">
  <main>
      <h2 class="fw-300 center-text recuadro-titulo"> Atracciones destacadas en Facatativá</h2>
      <div class="content-Anunc">
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/piedras del tunjo.jpg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>Piedras del Tunjo</h3>
                  <p>El Parque Arqueológico de Facatativá, también conocido como Piedras del Tunjo, es un conjunto de pictogramas cuyo origen exacto aún se desconoce</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>$10.000</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>Calle 5# 12A-10</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>8:00am - 4:00pm</p>
                          </li>
                      </ul>
                  </div>
                  <a href="http://www.colparques.net/FACA" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/KYSQA.jpg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>KYQA MHUYSQA</h3>
                  <p>El Parque Kyqa Mhuysqa es un espacio temático y centro de eventos inspirado en la cultura colombiana y nuestros antepasados muiscas</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>$49.000</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>Los llanitos, Zipalandia, Facatativá</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>sabados y domingo 10a.m–7p.m</p>
                          </li>
                      </ul>
                  </div>
                  <a href="https://acolap.org.co/kyqa-mhuysqa/" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/parque.jpeg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>Parque de los Niños</h3>
                  <p>El Parque de los Niños es un escenario recreo deportivo ubicado en la ciudad de Facatativá. Ofrece actividades para toda la familia y cuenta con instalaciones para el entretenimiento y la diversión.</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>gratis</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>Carrera 2 #1-102, en Facatativá</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>Abierto los jueves, viernes, sábados y domingos, con horarios específicos</p>
                          </li>
                      </ul>
                  </div>
                  <a href="https://www.facatativa-cundinamarca.gov.co/noticias/el-parque-de-los-ninos-un-lugar-para-la-diversion" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>      
      </div>
      <div class="content-Anunc">
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/camping.jpeg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>Camping Montañero</h3>
                  <p>Ubicado en la pintoresca Vereda Mancilla, el Camping Facatativá es el destino perfecto para aquellos que buscan una escapada natural en medio de la serenidad y belleza de la región. Este lugar ofrece una combinación ideal de tranquilidad, actividades al aire libre y contacto directo con la naturaleza, haciendo de cada visita una experiencia única y revitalizante.</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>$40.000</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>vereda Mancilla</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>8:00am - 8:00pm</p>
                          </li>
                      </ul>
                  </div>
                  <a href="https://www.campingmontanero.com/product/camping-facatativa/" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/KYSQA.jpg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>Plaza de Bolívar</h3>
                  <p>La Plaza de Bolívar de Facatativá es más que un simple espacio público; es el epicentro de la vida social, cultural e histórica de la ciudad. Con su arquitectura encantadora, sus monumentos significativos y su ambiente vibrante, la plaza es un lugar que tanto residentes como visitantes deben explorar para comprender la esencia de Facatativá.</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>gratis</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>Facatativá, Cundinamarca</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>todo el dia</p>
                          </li>
                      </ul>
                  </div>
                  <a href="https://www.tripadvisor.co/Attraction_Review-g1222953-d8692571-Reviews-Plaza_Simon_Bolivar-Facatativa_Cundinamarca_Department.html" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>
          <div class="anun">
              <img src="{{ url_for('static', filename='imagenes/cerro.jpeg') }}" alt="imagen atraccion">
              <div class="contenido_anun">
                  <h3>Cerro Manjui</h3>
                  <p>El Cerro Manjui, ubicado en el municipio de Facatativá, es un lugar que combina belleza natural, biodiversidad y valor histórico. Este cerro se erige como un destino ideal para los amantes de la naturaleza, los aventureros y aquellos que buscan un respiro del bullicio de la vida urbana.</p>
                  <div class="icono-info">
                      <ul>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/precio.png') }}" alt="icono precio">
                              <p>gratis</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/ubicacion.png') }}" alt="icono Ubicacion">
                              <p>Facatativá</p>
                          </li>
                          <li>
                              <img src="{{ url_for('static', filename='imagenes/horario.png') }}" alt="icono Horario">
                              <p>Todo el dia</p>
                          </li>
                      </ul>
                  </div>
                  <a href="https://es.wikiloc.com/rutas-mountain-bike/facatativa-cerro-manjui-18297315" class="boton boton-ver d_display" target="_blank">ver atraccion</a>
              </div>
          </div>      
      </div>
      <br>
  </main> 
</div>
{% endblock content %}

app/templates/blog.html
{% extends 'index.html' %}
{% import 'macro.html' as macros %}
<title>{% block title %}
     Blog
  {% endblock title %}</title>
{% block content %}
<main class="content">
    <h2 class="fw-300 center-text">Blog</h2>
    {% if blogs %}
    {% for blog in blogs %}
        {{ macros.render_bloginit(blog) }}
        <br><br>
    {% endfor %}
{% else %}
     <p>No hay publicaciones disponibles.</p>
{% endif %}
</main>
{% endblock content %}

app/templates/comentario.html
{% extends 'index.html' %}

{% block title %} {{ super() }} Comentario {% endblock %}

{% block content %}
    <div class="recuadro">
        <br>
        <div id="comentario" class="patron">
            <form action="{{ url_for('main.contactanos_view') }}" method="POST" class="form">
                {{ form.hidden_tag() }} <!-- Incluye el campo CSRF -->
                <h2 class="form_title">Envia tu comentario</h2>
                
                <!-- Nombre -->
                <div class="form_container">
                    <div class="form_group">
                        <input type="text" name="{{ form.name.name }}" class="form_input" placeholder=" " onkeypress="return SoloLetras(event)" onpaste="return false;" required>
                        {{ form.name.label(class="form_label") }}
                    </div>
                </div>
                <br>

                <!-- Email -->
                <div class="form_container">
                    <div class="form_group">
                        <input type="email" name="{{ form.email.name }}" class="form_input" placeholder=" " onkeypress="return Correo(event)" onpaste="return false;"required>
                        {{ form.email.label(class="form_label") }}
                    </div>
                </div>
                <br>

                <!-- Asunto -->
                <div class="form_container">
                    <div class="form_group">
                        <input type="text" name="{{ form.subject.name }}" class="form_input" placeholder=" " onkeypress="return SoloLetras(event)" onpaste="return false;"required>
                        {{ form.subject.label(class="form_label") }}
                    </div>
                </div>
                <br>

                <!-- Comentarios -->
                <div class="form_container">
                    <div class="form_group">
                        <textarea name="{{ form.comments.name }}" class="form_input" placeholder=" " rows="5" cols="25" onkeypress="return clave(event)" onpaste="return false;" required ></textarea>
                        {{ form.comments.label(class="form_label") }}
                    </div>
                </div>
                <br>

                <!-- Botón Enviar -->
                <div class="form_container">
                    <div class="form_group">
                        <button type="submit" class="boton boton-verc">{{ form.enviar.label.text }}</button>
                    </div>
                </div>
            </form>
        </div>
        <br>
        <script src="{{ url_for('static', filename='js/doc.js') }}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> <!-- Funcion de las alertas-->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,400;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <title>{% block title %}
     
      Facatur
    {% endblock title %}</title>
</head>
<body>
<header class="site-header init">
    <div class="content content-header">
        <div class="barra">
            <a href="{{ url_for('main.index') }}"> 
                <img src="{{ url_for('static', filename='imagenes/logov1.png') }}" alt="logotipo"> 
            </a>
            <nav class="busqueda"> 
              <a href="{{ url_for('main.nosotros') }}">Nosotros</a>
              <a href="{{ url_for('main.anuncios') }}"> Anuncios</a>
              <a href="{{ url_for('main.blog') }}"> Blog</a>
              <a href="{{ url_for('main.go_to_login') }}"> Inicio sesion</a>
            </nav>
        </div> <!-- naveg-->             
    </div>  <!-- content-->
</header>  
{% for message in get_flashed_messages() %}
<div class="alert alert-success alert-dismissible">
    <button type="button" data-dismiss="alert" class="close">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% block content %}
  
{% endblock content %}
<footer class="siste-footer content">
  <div class="content content-footer">
    <nav class="busqueda">
      <a href="{{ url_for('main.nosotros') }}">Nosotros</a>
      <a href="{{ url_for('main.anuncios') }}"> Anuncios</a>
      <a href="{{ url_for('main.blog') }}"> Blog</a>
    </nav>
    <b class="copy"> Todos los derechos reservados &copy;</b>
  </div>
</footer>
</body>
</html>